//
//  KeyStroke.h
//  GOSX Pro
//
//  Created by Andre Kalisch on 14.03.17.
//  Copyright © 2017 Andre Kalisch. All rights reserved.
//

#ifndef KeyStroke_h
#define KeyStroke_h

KeyStroke_t m_KeyStroke[MOUSE_COUNT + KEY_COUNT] =
{
    { "", "", "" },
    { "0", "=", "}" },
    { "1", "!", "" },
    { "2", "'", "" },
    { "3", "", "" },
    { "4", "$", "" },
    { "5", "%", "" },
    { "6", "&", "\\" },
    { "7", "/", "{" },
    { "8", "(", "[" },
    { "9", ")", "]" },
    { "a", "A", "" },
    { "b", "B", "" },
    { "c", "C", "" },
    { "d", "D", "" },
    { "e", "E", "" },
    { "f", "F", "" },
    { "g", "G", "" },
    { "h", "H", "" },
    { "i", "I", "" },
    { "j", "J", "" },
    { "k", "K", "" },
    { "l", "L", "" },
    { "m", "M", "" },
    { "n", "N", "" },
    { "o", "O", "" },
    { "p", "P", "" },
    { "q", "Q", "" },
    { "r", "R", "" },
    { "s", "S", "" },
    { "t", "T", "" },
    { "u", "U", "" },
    { "v", "V", "" },
    { "w", "W", "" },
    { "x", "X", "" },
    { "y", "Y", "" },
    { "z", "Z", "" },
    { "0", "0", "" },
    { "1", "1", "" },
    { "2", "2", "" },
    { "3", "3", "" },
    { "4", "4", "" },
    { "5", "5", "" },
    { "6", "6", "" },
    { "7", "7", "" },
    { "8", "8", "" },
    { "9", "9", "" },
    { "/", "/", "" },
    { "*", "*", "" },
    { "-", "-", "" },
    { "+", "+", "" },
    { "enter", "enter", "" },
    { ".", ">", "" },
    { "[", "{", "" },
    { "]", "}", "" },
    { ";", ":", "" },
    { "'", "@", "" },
    { "`", "", "" },
    { ",", "<", "" },
    { ".", ">", "" },
    { "/", "?", "" },
    { "\\", "|", "" },
    { "-", "_", "" },
    { "=", "+", "" },
    { "enter", "enter", "" },
    { "space", "space", "" },
    { "backspace", "backspace", "" },
    { "tab", "tab", "" },
    { "caps", "caps", "" },
    { "numlock", "numlock", "" },
    { "escape", "escape", "" },
    { "scrlock", "scrlock", "" },
    { "insert", "insert", "" },
    { "delete", "delete", "" },
    { "home", "home", "" },
    { "end", "end", "" },
    { "pageup", "pageup", "" },
    { "pagedown", "pagedown", "" },
    { "break", "break", "" },
    { "lshift", "lshift", "" },
    { "rshift", "rshift", "" },
    { "lalt", "lalt", "" },
    { "ralt", "ralt", "" },
    { "lctrl", "lctrl", "" },
    { "rctrl", "rctrl", "" },
    { "lwin", "lwin", "" },
    { "rwin", "rwin", "" },
    { "app", "app", "" },
    { "up", "up", "" },
    { "left", "left", "" },
    { "down", "down", "" },
    { "right", "right", "" },
    { "f1", "f1", "" },
    { "f2", "f2", "" },
    { "f3", "f3", "" },
    { "f4", "f4", "" },
    { "f5", "f5", "" },
    { "f6", "f6", "" },
    { "f7", "f7", "" },
    { "f8", "f8", "" },
    { "f9", "f9", "" },
    { "f10", "f10", "" },
    { "f11", "f11", "" },
    { "f12", "f12", "" },
    { "caps", "capstoggle", "" },
    { "numlock", "numlock", "" },
    { "scrlock", "scrlock", "" },
    { "mouse1", "mouse1", "" },
    { "mouse2", "mouse2", "" },
    { "mouse3", "mouse3", "" },
    { "mouse4", "mouse4", "" },
    { "mouse5", "mouse5", "" },
    { "mwheelup", "mwheelup", "" },
    { "mwheeldown", "mwheeldown", "" },
};

#endif /* KeyStroke_h */
